### PR TITLE
Add Lisp starter bot

### PR DESCRIPTION
**Pull request by HenryS1**
Adds a Lisp starter bot and bot runner.

### CODE REVIEW

**Comment by Mistborn94** [comment]
Hi @HenryS1 

Will you also submit a dockerfile to so the bot can run in a container? The guidelines are the same as for last year - https://github.com/EntelectChallenge/2019-Worms/tree/develop/starter-bots - we are working on updating the starter bots readme for this year.

**Comment by HenryS1** [comment]
@Mistborn94 I included a Dockerfile. However, I've noticed that that last year's docker example used `entelectchallenge/base:2019` and this year there doesn't appear to be a corresponding `entelectchallenge/base:2020` available (`manifest for entelectchallenge/base:2020 not found`). I suppose that's coming soon. What should I do?

**Comment by Mistborn94** [comment]
Please use the 2019 image :) If we make any changes to the base image we will update the docker files to use the new one :)

**Comment by HenryS1** [comment]
@Mistborn94 please take a look again. I've updated the Dockerfile to pull the Entelect base docker.

**Pull request merged**
