### PR TITLE
Added tests for speed penalties for conditions discussed in #70

### PR DESCRIPTION
**Pull request by kobus-v-schoor**
Hi again, thanks for adding the test cases, I played around with it a bit more and I think a might have found an issue. If I'm understanding correctly, both cars hit the cybertruck which should mean that both cars get the speed penalty. I've added test cases for this but it seems that only one of the cars is getting the speed penalty. Is this the intended behaviour?

### CODE REVIEW

**Comment by Jana-Wessels** [comment]
Hi Kobus,

 So for case |1|  |2|  |  |  |C| works and goes to |  |  |  |  |1|2|C| car 1 technically doesn't hit the cybertruck, rather it hits car 2 which hit the cybertruck. 

The standard collision logic does not include a speed reduction when you hit another car, although you will stay behind them (and essentially at the slower speed) unless you change lane at which point you will travel at your speed.

**Comment by kobus-v-schoor** [comment]
Ok thanks that makes sense for the same-lane case, but what should happen for the case where the one player turns into the lane? Sorry for being a bit of stickler on this, just want to make sure I don't miss some detail.

**Comment by KyleMcAllister** [comment]
Hi @kobus-v-schoor the same logic would apply. The player that makes contact with the cybertruck will have their speed reduced to 3, while the other player will be stuck behind the first player but not have their speed reduced.

As such, the assertions added to the test in this pull request are righfully causing the test to fail. So can I close this pr?

**Comment by kobus-v-schoor** [comment]
Hi @KyleMcAllister and @Jana-Wessels , as mentioned in [this forum post](https://forum.entelect.co.za/t/your-own-cybertruck-does-not-block-you/1035), I think I've been able to find a test case that triggers the possible original issue as I mentioned in issue #70. I've updated the original unit tests to match Louis Lotter's conditions and the test results match those of his match, also demonstrating what I believe to be the issue. I'm unsure why, but it seems that the original unit tests didn't trigger this problem

**Comment by kobus-v-schoor** [comment]
Hi, I think I've figured out why the original unit tests didn't trigger the issue. Player 1 was at position 700, Player 2 at position 702 and the cybertruck at position 706. The problem was that player 1 only had a speed of 5, so it never reached the cybertruck. So, player 1 would end up on position 705 (700 + speed of 5) so it doesn't hit the cybertruck, player 2 would then hit the truck and also end up on 705, after which the collision logic kicks in. With the updated unit tests both players have a high enough speed which enables both to hit the cybertruck, which triggers the issue.

**Comment by KyleMcAllister** [comment]
Hello @kobus-v-schoor happy with this. Just gonna move the tests around a bit after I merge this. Thanks for sorting it out :)

**Pull request merged**
